"""Build the wordmark as an SVG path.

The licensed cut has no accented glyphs at all — U+00E9 is mapped straight to
the plain `e` (verified with fontTools), so typing "Pyrenees" with accents
renders them silently missing. A wordmark is the one place that matters, so
it is drawn once here from the font's own outlines with the acutes added to
match, and shipped as a path rather than as text.

Run:  python3 scripts/gen-wordmark.py
Needs fontTools. Rewrites src/components/Wordmark.astro.
"""
import os
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.misc.transform import Transform

FONT = os.path.expanduser('~/Library/Fonts/Unica77LLTrial-Medium.otf')
OUT = os.path.join(os.path.dirname(__file__), '..', 'src', 'components', 'Wordmark.astro')

WORD = 'Pyrenees'
ACCENTS = {3, 5}          # zero-based letters that carry an acute: Pyr[é]n[é]es
TRACKING = -12            # units/em, matches the -0.015em the header text used

font = TTFont(FONT)
upem = font['head'].unitsPerEm
xh = font['OS/2'].sxHeight
gs = font.getGlyphSet()
cmap = font.getBestCmap()

pen_paths = []
x = 0
accent_at = []
for i, ch in enumerate(WORD):
    name = cmap[ord(ch)]
    spen = SVGPathPen(gs)
    gs[name].draw(TransformPen(spen, Transform().translate(x, 0)))
    pen_paths.append(spen.getCommands())
    if i in ACCENTS:
        # centre of the letter, for placing the mark
        accent_at.append(x + gs[name].width / 2)
    x += gs[name].width + TRACKING
adv = x - TRACKING

# The acute: a slanted bar sized off the type itself, so it reads as part of
# the face rather than as clip art. Weight follows the stem of `i`.
stem = 189 - 69
h = 150
w = stem * 0.92
slant = 0.42                     # run over rise
gap = 44                         # clear of the x-height
y0 = xh + gap
for cx in accent_at:
    x0 = cx - w / 2 - (h * slant) / 2
    pen_paths.append(
        f'M{x0 + h * slant:.1f} {y0 + h:.1f}'
        f'L{x0 + h * slant + w:.1f} {y0 + h:.1f}'
        f'L{x0 + w:.1f} {y0:.1f}'
        f'L{x0:.1f} {y0:.1f}Z'
    )

top = y0 + h
bottom = -220                    # the descender of `y`
vb = f'0 {-top} {adv:.0f} {top - bottom:.0f}'
# font space is Y-up, SVG is Y-down
d = ' '.join(pen_paths)

svg = f'''---
// GENERATED by scripts/gen-wordmark.py — do not hand-edit.
// The wordmark, drawn from the licensed outlines. It is a path and not text
// because the cut has no accented glyphs: U+00E9 maps to a plain `e`, so
// "Pyrénées" set as text loses both acutes without any warning. The marks
// here are drawn to the face's own stem weight and x-height.
// Height comes from --wm-h on any ancestor. It is set here rather than by
// the parent's class because Astro scopes styles per component: a class the
// header defines never reaches this element.
---
<svg
  class="wm"
  viewBox="{vb}"
  role="img"
  aria-label="Pyrénées"
  fill="currentColor"
  xmlns="http://www.w3.org/2000/svg"
><path transform="scale(1,-1)" d="{d}" /></svg>

<style>
  .wm {{
    display: block;
    height: var(--wm-h, 16px);
    width: auto;
  }}
</style>
'''
with open(OUT, 'w') as fh:
    fh.write(svg)
print('wrote', os.path.normpath(OUT))
print('viewBox', vb, '| advance', round(adv), '| upem', upem)
